# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b966a4f32188cee9c36ce476557d137eed4aa3b0136c29f2256ab286ed19b6f603de4ed185fc48ec3c44b6a92aebb92e0f0a8751aaf6c1b63985d764d3ef6a

test:
  secret_key_base: b5fb43262f7a63f4add8df0d468051f7c54d47ae28658fab2e37b38b77dcdea2245695ee8c6bba61f08946e202e9ebb21c748203f4a1a3c4d21fe1b25ef44d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
